### ISSUE TITLE
Support undo stack

### ISSUE THREAD

**Issue by Nordsoft91** [Nordsoft91/vcmi#7]
There is draft solution in mapping/CMapEditManager
Need to implement it and support in map editor

**Comment by DjWarmonger** [comment]
Oh well just realized. Wanted to use Qt for that: https://doc.qt.io/qt-5/qundo.html

**Comment by Nordsoft91** [comment]
Movement and erasing objects works.
Still needs implementation for:
 - terrain changes
 - object creation
 - object property change

**Comment by DjWarmonger** [comment]
Adding an erasing objects is a rabbit hole, as CMap does tons of bookkeeping for heroes, towns, quests etc.
